######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 8 22:24:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += diff.cpp
