######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 8 16:46:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

;CONFIG += debug

;QMAKE_CXXFLAGS += -std=c++0x

QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS += -O3
LIBS += -lboost_program_options

# Input
SOURCES += mean.cpp
